"""relations changed

Revision ID: 1783a5d5fb20
Revises: d2eace47898e
Create Date: 2023-07-02 20:10:02.946764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1783a5d5fb20'
down_revision = 'd2eace47898e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
