"""First migrate

Revision ID: 4c4f5a53f42c
Revises: 
Create Date: 2023-07-10 12:22:20.958243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4c4f5a53f42c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("books", sa.Column("create_date", sa.Date(), nullable=False))
    op.drop_column("books", "date")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "books", sa.Column("date", sa.DATE(), autoincrement=False, nullable=False)
    )
    op.drop_column("books", "create_date")
    # ### end Alembic commands ###
