"""relations changed

Revision ID: 8e12738e8e30
Revises: d78dd48c3e56
Create Date: 2023-07-02 19:34:41.929492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e12738e8e30'
down_revision = 'd78dd48c3e56'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
